language: c
compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get install -y libeditline-dev libreadline-dev build-essential libedit-dev

addons:
  apt:
    update: true

script: cc -std=c99 -Wall rml.c mpc.c -lm -lreadline -o rml

notifications:
  email: false

