language: c
compiler:
  - gcc
  - clang

addons:
  apt:
    update: true
    packages:
      - build-essential
      - make
      - gcc
      - libreadline6
      - libeditline-dev
      - libreadline-dev
      - libedit-dev

script: make

notifications:
  email: false

